### ISSUE TITLE
Lombok not working with NB 25

### ISSUE THREAD

**Issue by sephiroth-j** [apache/netbeans#8269]
### Apache NetBeans version

Apache NetBeans 25 release candidate

### What happened

After updating Netbeans from 24 to 25 (**Final, not RC**), I'm getting errors regarding lombok on all classes - even on empty classes without lombok.

```
Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: Could not initialize class lombok.javac.Javac
  	at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:174)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:96)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:995)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:623)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:752)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:846)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:109)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1189)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1302)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272)
  	at org.netbeans.lib.nbjavac.services.NBJavaCompiler.processAnnotations(NBJavaCompiler.java:64)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1174)
  	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:348)
  	at com.sun.tools.javac.api.JavacTaskImpl.enter(JavacTaskImpl.java:282)
  	at org.netbeans.modules.java.source.parsing.JavacParser.moveToPhase(JavacParser.java:742)
  	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:536)
  	at org.netbeans.modules.java.source.parsing.JavacParser.getResult(JavacParser.java:140)
  	at org.netbeans.modules.parsing.impl.TaskProcessor.callGetResult(TaskProcessor.java:608)
  	at org.netbeans.modules.parsing.impl.SourceCache.getResult(SourceCache.java:241)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.run(TaskProcessor.java:775)
  	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:288)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$RequestPerformer.execute(TaskProcessor.java:702)
  	at org.netbeans.modules.parsing.impl.TaskProcessor$CompilationJob.run(TaskProcessor.java:663)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1403)
  	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
  	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:287)
  	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2018)
  Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldException: com.sun.tools.javac.code.TypeTag :: UNKNOWN [in thread "RepositoryUpdater.worker"]
  	at lombok.permit.Permit.getField(Permit.java:144)
  	at lombok.javac.JavacTreeMaker$SchroedingerType.getFieldCached(JavacTreeMaker.java:171)
  	at lombok.javac.JavacTreeMaker$TypeTag.typeTag(JavacTreeMaker.java:259)
  	at lombok.javac.Javac.<clinit>(Javac.java:187)
  	at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:174)
  	at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:96)
  	at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:160)
  	at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:213)
  	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:64)
  	at org.netbeans.modules.java.source.indexing.APTUtils$ErrorToleratingProcessor.init(APTUtils.java:995)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:623)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:752)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:846)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:109)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1189)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1302)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272...
```

### Language / Project Type / NetBeans Component

Java Maven Project

### How to reproduce

1. Download NB25 from https://dlcdn.apache.org/netbeans/netbeans/25/netbeans-25-bin.zip
2. Import attached demo project [nb25-lombok-issue.zip](https://github.com/user-attachments/files/18907296/nb25-lombok-issue.zip)
3. open one of the sample classes
4. you will see the warning next to the class name

![Image](https://github.com/user-attachments/assets/b5a8aea1-0d41-43d1-a552-0964927f215c)

### Did this work correctly in an earlier version?

Apache NetBeans 24

### Operating System

Win 10 x64

### JDK

Java: 21.0.4; OpenJDK 64-Bit Server VM 21.0.4+7-LTS

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

**Comment by neilcsmith-net** [comment]
See #8221

**Comment by sephiroth-j** [comment]
So this is expected even when compile on save is disabled and neither the project nor NetBeans use Java 24?

**Comment by neilcsmith-net** [comment]
Yes. The NetBeans parser uses javac from Java 24, so cannot work until there is a Lombok version that supports that.
