### ISSUE TITLE
Impossible creating web service from wsdl

### ISSUE THREAD

**Issue by lordpixel79** [apache/netbeans#3753]
### Apache NetBeans version

Apache NetBeans 13

### What happened

I want to create web service from wsdl.
The wsdl is correct (same procedure works well on NB12.0 on jdk8 )

With Netbeans 13 , on a web maven project, i try to create web service from wsdl.
New --> Web Services --> Web Service from WSDL
When i chose wsdl this message appear: "There is no port in specified WSDL file" (i repeat same procedure on NB12.0 and JDK8 works fine).
There is also an exception ide:

java.lang.NoClassDefFoundError: Could not initialize class com.sun.tools.ws.wscompile.Options$Target
	at com.sun.tools.ws.wscompile.Options.<init>(Options.java:174)
	at com.sun.tools.ws.wscompile.WsimportOptions.<init>(WsimportOptions.java:84)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.generateWsdlModel(WsdlModeler.java:172)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.generateWsdlModel(WsdlModeler.java:168)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.access$000(WsdlModeler.java:53)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler$1.run(WsdlModeler.java:78)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

### Did this work correctly in an earlier version?

Apache NetBeans 12.3 or earlier

### Operating System

Linux fedora

### JDK

Jdk 11

### Apache NetBeans packaging

Apache NetBeans binary zip

### Are you willing to submit a pull request?

No

### Code of Conduct

Yes

**Comment by pepness** [comment]
Possibly duplicate for [ISSUE-3622](https://github.com/apache/netbeans/issues/3622), please test latest master.
