### ISSUE TITLE
Apache Netbeans (all versions) do not support the generation of a Web Service from WSDL

### ISSUE THREAD

**Issue by roberto-cisternino** [apache/netbeans#3622]
### Apache NetBeans version

Apache NetBeans 12.6

### What happened

Using Netbeans 8.2 it was very easy to generate a Web Service from WSDL, this is impossible using Apache Netbeans (any release).
I provide a screenshot from Netbeans 8.2 and one from Netbeans 12.5.
By using the "New Web Service from WSDL" feature an error is shown "**There is no port in specified WSDL file**" even if the port is correctly specified.

![image](https://user-images.githubusercontent.com/29631792/154471942-5431a0a7-467d-4f7d-b347-6f936436aee3.png)

**The IDE log shows also an error:**

SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler$1
java.lang.NoClassDefFoundError: Could not initialize class com.sun.tools.ws.wscompile.Options$Target
	at com.sun.tools.ws.wscompile.Options.<init>(Options.java:174)
	at com.sun.tools.ws.wscompile.WsimportOptions.<init>(WsimportOptions.java:84)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.generateWsdlModel(WsdlModeler.java:172)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.generateWsdlModel(WsdlModeler.java:168)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler.access$000(WsdlModeler.java:53)
	at org.netbeans.modules.websvc.api.jaxws.wsdlmodel.WsdlModeler$1.run(WsdlModeler.java:78)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

This error is pretty strange because the wsimport has the right path to reach jaxws-tools.jar  (see ${libs.jaxws21.classpath} )

**The same action using Netbeans 8.2 is successful.**

![image](https://user-images.githubusercontent.com/29631792/154471858-b5314b2c-854f-43d4-935a-f8ed21deacb4.png)

NOTE: I am talking about Java 1.8 thus Netbeans 12.6 is not taken into consideration here because there are many other problems working with 1.8 on a JDK11 Netbeans installation.

### How to reproduce

From a WAR or EJB project select New - Other - Web Service - Web Service from WSDL

Any WSDL can be used such as a public one:
https://www.learnwebservices.com/services/hello?WSDL

Fill up the other parameter like the package and confirm the ws import.

The result is always the error above explained "There is no port in specified WSDL file"

### Did this work correctly in an earlier version?

No

### Operating System

Windows 10

### JDK

8

### Apache NetBeans packaging

Apache NetBeans provided installer

### Code of Conduct

Yes

**Comment by pepness** [comment]
Hi Roberto,
This is fixed with [PR-3607](https://github.com/apache/netbeans/pull/3607), can you please check it out?
![NB-Issue-3622](https://user-images.githubusercontent.com/9832133/154822314-310a0905-947a-4b39-aa42-6956989d104c.png)

**Comment by roberto-cisternino** [comment]
Well done !
